#!/bin/bash
# this if statement is needed for bsub
if [ -f /etc/profile.d/modules.sh ]; then
   source /etc/profile.d/modules.sh
fi
module load bowtie2/2.3.4.1
module load java-sdk-1.8.0
module load samtools-1.1
module load R/3.1.1
module load python-2.7.9
module load picard-1.96
PATH=\
/home/esanford/software/bedtools2/bin:\
$PATH \
$@
module unload bowtie2/2.3.4.1
module unload java-sdk-1.8.0
module unload samtools-1.1
module unload R/3.1.1
module unload python-2.7.9
module unload picard-1.96